wazuh/qa-integration-framework

requirements.txt
src/wazuh_testing/constants/paths/__init__.py
src/wazuh_testing/constants/paths/binaries.py
src/wazuh_testing/constants/paths/configurations.py
src/wazuh_testing/constants/paths/logs.py
src/wazuh_testing/constants/paths/variables.py
src/wazuh_testing/global_parameters.py
src/wazuh_testing/modules/analysisd/utils.py
src/wazuh_testing/modules/execd/__init__.py
src/wazuh_testing/tools/file_monitor.py
src/wazuh_testing/utils/configuration.py
src/wazuh_testing/utils/mocking.py
src/wazuh_testing/utils/services.py

|Related Issue|
|---|
| https://github.com/wazuh/qa-integration-framework/issues/15|
This PR applies the platform constants on all the _platform conditionals_, it also adds a default timeout when the tests are being executed on Windows and gives 10 more seconds to the `FileMonitor` default monitor.

Add `pywin32` and apply platform constants

---

README.md
src/wazuh_testing/tools/mitm.py

| Related issue |
|----------------|
| #17                |
This PR removes the deprecated function call `ssl.wrap_socket()` avoiding the raise of warning logs when it is called. Now only the non-deprecated functions from the `ssl` library are used.
closes #17 
In the previous code when `execd` ITs are executed, a Warning is raised because the `AuthdSimulator` calls the deprecated function.
> Job of the execution with the error: [`10005021493`]( https://github.com/wazuh/wazuh/actions/runs/5489868617/jobs/10005021493)
```vim
============================= test session starts =============================
platform win32 -- Python 3.10.11, pytest-7.1.2, pluggy-1.2.0
rootdir: C:\wazuh\tests\integration, configfile: pytest.ini
plugins: html-3.1.1, metadata-3.0.0
collected 6 items / 4 deselected …
```

Remove deprecated `ssl` function call

---

requirements.txt

This PR fixes the `cython_sources` at the installation of the `PyYaml` requirement. The error happens because PyYaml 5.x.x is not compatible with the new `Cython3` version, so it must be updated to `6.0.1`

upgrade pyyaml requirement to 6.0.1

---

src/wazuh_testing/tools/simulators/agent_simulator.py

|Related Epic       |           Related issue|
|-----------------------| ---------------------------|
|  wazuh/wazuh#17427    |   wazuh/wazuh#17700     |
This PR includes all the necessary changes to move the rootcheck integration tests from wazuh-qa to this repository. This test requires (https://github.com/wazuh/qa-integration-framework/pull/22).
And, finally, this PR just avoid this error:
```
self.socket.send(length + event)
OSError: [Errno 9] Bad file descriptor
```

17700 refactor and migrate rootcheck integration tests

---

src/wazuh_testing/tools/simulators/remoted_simulator.py

Now the `RemotedSimulator` saves the complete request context with the full _request received_, _request message_ and _response message_. This modification will be helpful in cases where we need to check a response from the agent, or we want to validate the complete request in a test.
Also, a `request_counter` was added as this will be required by some custom messages from the simulator to the agent.

Improve `RemotedSimulator`

---

src/wazuh_testing/modules/api/utils.py

|---|
| Closes https://github.com/wazuh/wazuh/issues/18651 |
Changed the `login` function `login_attempts` parameter to make more than 1 attempt by default. Replaced the `sleep_time` parameter with `backoff_factor` to use a retry strategy for the requests in case of receiving connection refused errors.
- https://github.com/wazuh/wazuh/actions/runs/6261596516
- https://github.com/wazuh/wazuh/actions/runs/6261597845
- https://github.com/wazuh/wazuh/actions/runs/6261598968

Add retries to login and change default values

---

src/wazuh_testing/data/statistics_template/manager_statistics_format_test_module/wazuh-db_template.json

|-------------|
|      Closes https://github.com/wazuh/wazuh-qa/issues/4217       |
Removed the deprecated commands `get-groups-integrity`, `select-agent-group` and `find-group` from the tests.
<details><summary>Tests execution</summary>
Build: https://github.com/wazuh/wazuh/actions/runs/6419146728/job/17428378145?pr=19420
```console
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0
rootdir: /home/runner/work/wazuh/wazuh/tests/integration, configfile: pytest.ini
plugins: metadata-3.0.0, html-3.1.1
collected 61 items / 3 deselected / 58 selected
test_api/test_config/test_DOS_blocking_system/test_DOS_blocking_system.py . [  1%]
[  1%] …
```

Remove group commands

---

src/wazuh_testing/tools/mitm.py

|---|
| https://github.com/wazuh/qa-integration-framework/issues/41 |
| https://github.com/wazuh/wazuh/issues/17696 |
During the development of the Agentd IT test migration, it was found, RemotedSimulator was not mocking properly the UDP connection. It was due to the MITM object not sending a response to the agent. This PR fixes it and lets the agent establish the connection as expected.
Now the following logs appear using UDP:
```
2024/01/10 22:29:31 wazuh-agentd[29667] start_agent.c:93 at connect_server(): INFO: Trying to connect to server ([127.0.0.1]:1514/udp).
2024/01/10 22:29:31 wazuh-agentd[29667] start_agent.c:365 at agent_handshake_to_server(): INFO: (4102): Connected to the server ([127.0.0.1]:1514/udp).
2024/01/10 22:29:31 wazuh-agentd[29667] pthreads_op.c:45 at …
```

Fix RemotedSimulator udp connections

---

CHANGELOG.md
src/wazuh_testing/data/statistics_template/manager_statistics_format_test_module/wazuh-db_template.json

| Related issue |
|--|
|https://github.com/wazuh/wazuh/issues/21303|
Update the statistics template in the API test after the core team removed all references of the legacy vulnerability detector module.

Update wazuh-db statistics template

---

CHANGELOG.md

|---|
|Closes https://github.com/wazuh/wazuh/issues/22656 |
Removes a log that will now be added in `4.8.0` ([PR](https://github.com/wazuh/qa-integration-framework/pull/131)).

Remove log to be added 4.8.0

---

CHANGELOG.md
src/wazuh_testing/tools/simulators/agent_simulator.py

| Issue |
|---------|
| https://github.com/wazuh/wazuh-qa/issues/1266|
Fixes the response of the `agent simulator` for the active-response configuration messages.

Fixes response of agent_simulator for active-response config request

---

src/wazuh_testing/modules/logcollector/utils.py
src/wazuh_testing/tools/monitors/file_monitor.py
src/wazuh_testing/utils/file.py

Closes #130 
This PR addresses the need for rigorous integration testing of the `journald` log collection feature as outlined in Issue https://github.com/wazuh/wazuh/issues/12862. The enhancements made to the Wazuh QA framework through this PR are designed to ensure that the `journald` log collection functionality is thoroughly tested, verifying its reliability and integration within the existing Wazuh ecosystem.
The main goal of this PR is to adapt and expand the current Wazuh QA framework to support integration testing specifically tailored for the `journald` log collection feature. By doing so, we aim to safeguard the robustness and effectiveness of this new feature, ensuring it performs as expected in diverse scenarios and configurations.
1. **Regex-based File Manipulation:**
- Added …

Extend QA Framework for Integration Testing of Journald Log Collection

---

src/wazuh_testing/modules/aws/data_generator.py
src/wazuh_testing/modules/aws/utils.py
src/wazuh_testing/tools/db_administrator.py
src/wazuh_testing/utils/database.py
src/wazuh_testing/utils/db_queries/aws_db.py

Closes #150. 
- Modifies S3 data generation methods and functions to generate resources for any specified region with the possibility to include `prefix` or `suffix`.
- Removes the `boto3` client instantiations from the framework, making it the responsibility of the executed tests to instantiate and pass them accordingly.
- Fixes related AWS database functions that were not correctly used after the rebase of the epic branch.
<details><summary>Current working tests execution</summary>
```console
root@vagrant:/# pytest -x /wazuh/tests/integration/test_aws/test_log_groups.py 
=================================================================== test session starts ====================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.4.0 …
```

Allow setting different regions to generated AWS resources

---

src/wazuh_testing/modules/logcollector/utils.py

Closes #152 
This pull request updates the Wazuh QA Integration Framework to reflect recent changes in the Logcollector configuration API, specifically adapting the validation of the API response to accommodate the renaming of the `target` field to `socket`. This change was introduced in the Wazuh core by PR [wazuh/wazuh#17664](https://github.com/wazuh/wazuh/pull/17664) to enhance clarity in the configuration settings.
- **Validation Script Updates**:
- The validation checks within the QA Integration Framework have been updated to replace references from `target` to `socket`. This ensures that our integration tests are consistent with the latest API specifications.
- To ensure the QA Integration Framework accurately reflects the changes made to the Logcollector configuration API.
- To …

Align validation with Logcollector API's socket Field Update

---

requirements.txt
src/wazuh_testing/scripts/pytest_coverage.py

|---|
| Closes https://github.com/wazuh/wazuh/issues/23558 |
Adds a script and the dependencies to get the Python unit tests coverage.
https://github.com/wazuh/wazuh/actions/workflows/python-unit-tests-coverage.yml
> The `Run workflow` option appears only after it's merged.
<details><summary>Results</summary>
| | | | | |
|--|--|--|--|--|
| **Name** | **Stmts** | **Miss** | **Cover** | **Status** |
| framework/__init__.py | 0 | 0 | 100% | :green_square: |
| framework/scripts/__init__.py | 0 | 0 | 100% | :green_square: |
| framework/scripts/agent_groups.py | 177 | 17 | 90% | :green_square: |
| framework/scripts/agent_upgrade.py | 115 | 9 | 92% | :green_square: |
| framework/scripts/cluster_control.py | 133 | 1 | 99% | :green_square: |
| framework/scripts/rbac_control.py | 64 …

Add python unit tests coverage script

---

requirements.txt

Issue related: https://github.com/wazuh/wazuh/issues/23148
In this PR we are modifying the required version of the py module in order to support the macOS integration tests, which now have python version 3.11.

Upgrade `py` module in requirements

---

src/wazuh_testing/modules/fim/patterns.py

In this PR we are adding the following callback pattern to detect warnings related to unsupported name (nonUTF8)
`IGNORING_DUE_TO_INVALID_NAME = r".*Ignoring file '(.*)' due to unsupported name.*"`
Testing will be done in the related wazuh/wazuh PR which includes tests:

New regex callback in FIM tests to find events for invalid path names

---

src/wazuh_testing/modules/api/patterns.py

Adds an escape character to match the new log format for the API start-up correctly.
```console
2024/08/20 13:07:31 INFO: Listening on ['0.0.0.0', '::']:55000.
```

Adapt regex for double IP stack

---

VERSION.json
setup.py

|--|
| #302 |
Adds the `VERSION.json` file to comply with the standardization of how the Wazuh repositories handle versions and revisions. It also modifies the `setup.py` file to get the package's version from the newly added file.

Add version file for package installation

---

VERSION.json
setup.py

|--|
| #302 |
Adds the `VERSION.json` file to comply with the standardization of how the Wazuh repositories handle versions and revisions. It also modifies the `setup.py` file to get the package's version from the newly added file.

Add version file for package installation in default branch

---

.gitignore
VERSION.json
tools/repository_bumper.sh

This PR closes #341. Adds a script to bump the version and revision of `VERSION.json`.
```console
➜  qa-integration-framework git:(enhancement/341-bumper-script) ./tools/repository_bumper.sh --help
Usage: ./tools/repository_bumper.sh <new_version> <stage>
```
```console
➜  qa-integration-framework git:(enhancement/341-bumper-script) ./tools/repository_bumper.sh 4.13.0 alpha1
Current version: 4.13.0
Current stage: alpha0
➜  qa-integration-framework git:(enhancement/341-bumper-script) ✗ cat tools/repository_bumper_2025-04-11_17-30-01.log
Modified files:
VERSION.json: version 4.13.0 -> 4.13.0, stage alpha0 -> alpha1
```
```diff
diff --git a/VERSION.json b/VERSION.json
index 4d32c49..3747a84 100644
--- a/VERSION.json
+++ b/VERSION.json
@@ -1,4 +1,4 @@
{
"version": "4.13.0",
-  "stage": …
```

Add bumper script

---

src/wazuh_testing/utils/mocking.py

This pull request updates the agent creation mock logic in the QA framework to align with recent changes in the Wazuh manager. From now on, newly registered agents are assigned to the `"default"` group by default, unless a different group is specified.
This ensures consistency between the testing environment and the actual behavior of the Wazuh manager when enrolling agents.
- Modify the mock responsible for agent creation to assign the `"default"` group automatically if no group is explicitly provided.
- Adjust related test data generation to reflect the default group assignment logic.
- All QA tests using the agent creation mock now produce agents with a group assignment (`"default"`), matching the expected behavior of the Wazuh manager.
- Existing tests that specify a group remain …

Assign new agents to the "default" group in agent creation mock

---

src/wazuh_testing/modules/authd/utils.py

Due to the recent refactor for the authd module https://github.com/wazuh/wazuh/issues/28908, the server now checks for newline character.

Fix authd integration tests

---

CHANGELOG.md

It was added the issue https://github.com/wazuh/qa-integration-framework/pull/400 to the 4.14.1 CHANGELOG.md.

Add syscollector issue to CHANGELOG.md in 4.14.1

---

src/wazuh_testing/scripts/pytest_coverage.py

Part of https://github.com/wazuh/wazuh/issues/31472. Removes the `integrations` folder from the test coverage script.

Remove integrations from test coverage

---

src/wazuh_testing/tools/simulators/agent_simulator.py

Closes https://github.com/wazuh/wazuh/issues/31580. 
- It changes the remoted message in the Agent simulator according to the fix at https://github.com/wazuh/wazuh/pull/31254.
<details><summary>Test remoted Tier 2</summary>
```console
root@ubuntu-jammy:/qa-integration-framework# git branch
* bug/31580-integration-test-remoted-tier-2
/var/varroot@ubuntu-jammy:/wazuh/tests/integration# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.13.0"
WAZUH_REVISION="beta2"
WAZUH_TYPE="server"
========================================= test session starts ==========================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.6.0
rootdir: /wazuh/tests/integration
configfile: pytest.ini
plugins: html-3.1.1, metadata-3.1.1, cov-4.1.0
collected 189 items / 139 deselected / 50 …
```

Modify remoted message in agent simulator

---

src/wazuh_testing/constants/platforms.py
src/wazuh_testing/data/events_template/keepalives.txt
src/wazuh_testing/tools/simulators/agent_simulator.py
src/wazuh_testing/utils/services.py

This PR removes the GitHub Actions workflows for specials as these are being deprecated as Tier 3 operating systems. Issue: https://github.com/wazuh/wazuh/issues/31714

Remove Tier 3 OS: Deprecate specials
