- src/wazuh_testing/tools/monitors/base_monitor.py
- src/wazuh_testing/tools/monitors/file_monitor.py
- src/wazuh_testing/tools/monitors/queue_monitor.py
- src/wazuh_testing/tools/simulators/authd_simulator.py
- src/wazuh_testing/tools/simulators/base_simulator.py
- src/wazuh_testing/tools/simulators/remoted_simulator.py
Add `BaseMonitor` class to ensure monitor-s behavior.
> Add BaseMonitor class

- src/wazuh_testing/tools/monitors/file_monitor.py
This fixes the failing executions on windows
> fix timeout in file_monitor

- setup.py
> Change main version to 4.8.0

- setup.py
> Bump version to 4.7.0

- src/wazuh_testing/utils/database.py
- src/wazuh_testing/utils/db_queries/agent_db.py
- src/wazuh_testing/utils/sockets.py
Related to: https://github.com/wazuh/wazuh/issues/17700  
This PR includes:
In database -  get_sqlite_query_result
In sockets - send_request_socket
necessary changes to give support to the rootcheck migrated tests in the wazuh/wazuh repository. Those tests will use this new structure.
> Migrate rootcheck dependencies

- CHANGELOG.md
- setup.py
|--|
| #54 |
Bump main branch to 4.9.0
> Bump main branch to 4.9.0

- src/wazuh_testing/data/all_disabled_ossec.conf
| Related Issue |
|--------|
| wazuh/wazuh#20172 | 
This PR closes wazuh/wazuh#20172. Replace the `vulnerability-detector` configuration by the new `vulnerability-detection`.
[Integration tests for API - Tier 0 and 1](https://github.com/wazuh/wazuh/actions/runs/6827027115)
> Replace vulnerability-detector by the new key

- CHANGELOG.md
- setup.py
|:--:|
| https://github.com/wazuh/qa-integration-framework/issues/68 |
Merge 4.7.1 into 4.7.2
> Merge 4.7.1 into 4.7.2

- CHANGELOG.md
- setup.py
|--|
| #77 |
Bump `setup.py` and update the changelog to `4.8.2` version.
> Bump to 4.8.2 version

- CHANGELOG.md
- src/wazuh_testing/data/statistics_template/manager_statistics_format_test_module/wazuh-db_template.json
|:--:|
| https://github.com/wazuh/qa-integration-framework/issues/91 |
Merge 4.8.0 into 4.8.1
> Merge 4.8.0 into 4.8.1

- CHANGELOG.md
- src/wazuh_testing/data/statistics_template/manager_statistics_format_test_module/wazuh-db_template.json
|:--:|
| https://github.com/wazuh/qa-integration-framework/issues/91 |
Merge 4.8.1 into 4.8.2
> Merge 4.8.1 into 4.8.2

- CHANGELOG.md
- src/wazuh_testing/data/statistics_template/manager_statistics_format_test_module/wazuh-db_template.json
|:--:|
| https://github.com/wazuh/qa-integration-framework/issues/91 |
Merge 4.8.2 into main
> Merge 4.8.2 into main

- CHANGELOG.md
- setup.py
|--|
| #96 |
Bump main branch to 5.0.0
> Bump main branch to 5.0.0

- CHANGELOG.md
- setup.py
|--|
| #98 |
Bump 4.7.3 version and update changelog.
> Bump to 4.7.3, update changelog

- src/wazuh_testing/modules/fim/patterns.py
- src/wazuh_testing/modules/syscheck/configuration.py
- src/wazuh_testing/tools/monitors/file_monitor.py
- src/wazuh_testing/tools/monitors/queue_monitor.py
- src/wazuh_testing/utils/file.py
|---|
|https://github.com/wazuh/qa-integration-framework/issues/20|
Necessary changes to run correctly ignore cases for FIM ITs
> Event type added msg chaged

- src/wazuh_testing/utils/services.py
This PR applies the latest changes to fix the service control function for Windows agents.
> Fix service control function for Windows

- src/wazuh_testing/modules/fim/patterns.py
- src/wazuh_testing/utils/file.py
|---|
|https://github.com/wazuh/qa-integration-framework/issues/20|
Necessary changes to run correctly ignore cases for FIM ITs
> Patterns added for inotify and max eps cases

- src/wazuh_testing/constants/paths/binaries.py
- src/wazuh_testing/modules/agentd/patterns.py
- src/wazuh_testing/modules/execd/active_response/patterns.py
- src/wazuh_testing/modules/modulesd/__init__.py
- src/wazuh_testing/modules/modulesd/vulnerability_detector/__init__.py
- src/wazuh_testing/modules/remoted/patterns.py
- src/wazuh_testing/tools/certificate_controller.py
- src/wazuh_testing/tools/simulators/authd_simulator.py
- src/wazuh_testing/utils/secure_message.py
- src/wazuh_testing/utils/sockets.py
|---|
|https://github.com/wazuh/wazuh/issues/19088|
This PR includes the necessary changes to be able to run the enrollment IT using the new QA framework.
> Support enrollment IT

- CHANGELOG.md
- setup.py
|--|
| #137 |
Bump 4.7.4 branch.
> Bump to 4.7.4, update changelog

- CHANGELOG.md
- setup.py
|--|
| #160  |
Bump 4.7.5 branch.
> Bump to 4.7.5, update changelog

- src/wazuh_testing/modules/fim/patterns.py
|---|
|https://github.com/wazuh/wazuh/issues/17881|
Log patterns is added for windows_system_folder_redirection
> Pattern added for windows_system_folder_redirection tests

- src/wazuh_testing/modules/fim/patterns.py
|---|
|https://github.com/wazuh/wazuh/issues/22761|
added pattern to test_restrict_suite
> pattern to test-fim-restrict

- CHANGELOG.md
- src/wazuh_testing/constants/paths/api.py
|---|
|Closes https://github.com/wazuh/wazuh/issues/22608|
Updates the API script path to accommodate to the file name change in https://github.com/wazuh/wazuh/pull/23222.
> Update API script path

- CHANGELOG.md
|:--:|
| https://github.com/wazuh/qa-integration-framework/issues/174 |
Merge 4.8.0 into 4.9.0
> Merge 4.8.0 into 4.9.0

- CHANGELOG.md
- requirements.txt
- src/wazuh_testing/constants/aws.py
- src/wazuh_testing/constants/paths/api.py
- src/wazuh_testing/constants/paths/aws.py
- src/wazuh_testing/modules/aws/data_generator.py
- src/wazuh_testing/modules/aws/patterns.py
- src/wazuh_testing/modules/aws/utils.py
- src/wazuh_testing/modules/fim/patterns.py
- src/wazuh_testing/modules/fim/utils.py
- src/wazuh_testing/modules/logcollector/utils.py
- src/wazuh_testing/tools/db_administrator.py
- src/wazuh_testing/tools/monitors/file_monitor.py
- src/wazuh_testing/utils/database.py
- src/wazuh_testing/utils/db_queries/aws_db.py
- src/wazuh_testing/utils/file.py
- src/wazuh_testing/utils/random.py
|:--:|
| https://github.com/wazuh/qa-integration-framework/issues/174 |
Merge 4.9.0 into main
> Merge 4.9.0 into main

- src/wazuh_testing/constants/paths/sockets.py
- src/wazuh_testing/modules/fim/configuration.py
- src/wazuh_testing/modules/fim/patterns.py
- src/wazuh_testing/modules/fim/utils.py
- src/wazuh_testing/utils/file.py
- src/wazuh_testing/utils/string.py
|---|
|https://github.com/wazuh/wazuh/issues/22760|
This PR adds log patterns and error messages for the test_report_changes tests
> Patterns added for test_report_changes(FIM) tests

- CHANGELOG.md
- setup.py
|--|
| #177 |
Bump 4.8.1 branch.
> Bump to 4.8.1, update changelog

- CHANGELOG.md
|:--:|
| https://github.com/wazuh/qa-integration-framework/issues/185 |
Merge 4.8.1 into 4.9.0
> Merge 4.8.1 into 4.9.0

- CHANGELOG.md
- setup.py
|--|
| #189  |
Bump 4.10.0 branch.
> Bump version to 4.10.0

- src/wazuh_testing/modules/fim/patterns.py
Reverts wazuh/qa-integration-framework#207
> Revert "Merge 4.9.0 into main"

- src/wazuh_testing/modules/fim/patterns.py
Reverts wazuh/qa-integration-framework#211
> Restore "Merge 4.9.0 into main"

- CHANGELOG.md
- setup.py
|--|
| #214  |
Bump 4.9.1 branch.
> Bump to 4.9.1, update changelog

- src/wazuh_testing/modules/fim/configuration.py
- src/wazuh_testing/modules/fim/patterns.py
|---|
|https://github.com/wazuh/wazuh/issues/23403|
In this PR we are modifying and adding some integration tests of the new framework related to the FIM report_changes setting.
These changes are due to this other issue that modified a little bit the behavior and some messages: https://github.com/wazuh/wazuh/issues/9448
> Added new patterns related to report_changes

- CHANGELOG.md
- src/wazuh_testing/modules/fim/configuration.py
- src/wazuh_testing/modules/fim/patterns.py
|:--:|
| https://github.com/wazuh/qa-integration-framework/issues/224 |
Merge 4.9.0 into 4.9.1
> Merge 4.9.0 into 4.9.1

- CHANGELOG.md
- src/wazuh_testing/modules/api/patterns.py
- src/wazuh_testing/modules/fim/configuration.py
- src/wazuh_testing/modules/fim/patterns.py
|:--:|
| https://github.com/wazuh/qa-integration-framework/issues/224 |
Merge 4.9.1 into 4.10.0
> Merge 4.9.1 into 4.10.0

- CHANGELOG.md
- src/wazuh_testing/modules/api/patterns.py
- src/wazuh_testing/modules/fim/configuration.py
- src/wazuh_testing/modules/fim/patterns.py
|:--:|
| https://github.com/wazuh/qa-integration-framework/issues/224 |
Merge 4.10.0 into main
> Merge 4.10.0 into main

- CHANGELOG.md
- setup.py
|--|
| #233  |
Bump 4.9.2 branch.
> Bump to 4.9.2, update changelog

- CHANGELOG.md
- setup.py
|--|
| #244  |
Bump 4.10.2 branch.
> Bump to 4.10.2, update changelog

- requirements.txt
- src/wazuh_testing/scripts/pytest_coverage.py
|---|
| https://github.com/wazuh/wazuh/issues/26466 |
Adds a script and the dependencies to get the Python unit tests coverage.
> Add script for pytest coverage test

- CHANGELOG.md
- setup.py
|--|
| #271  |
Bump 4.10.3 branch.
> Bump to 4.10.3, update changelog

- CHANGELOG.md
- setup.py
|--|
| #279 |
Bump 4.10.1 branch.
> Bump to 4.10.1, update changelog

- CHANGELOG.md
- setup.py
|--|
| #278 |
Bump 4.12.0 branch.
> Bump to 4.12.0, update changelog

- CHANGELOG.md
- setup.py
|--|
| #292 |
Bump 4.10.2 branch.
> Bump to 4.10.2

- CHANGELOG.md
- setup.py
* Bump version to 4.11.1
* Update changelog
> Bump to 4.11.1

- src/wazuh_testing/constants/paths/variables.py
- src/wazuh_testing/utils/services.py
Since a new version file is now in place, this PR updates some scripts to use it.
> Use new VERSION.json file

- src/wazuh_testing/constants/paths/variables.py
- src/wazuh_testing/utils/services.py
This PR ports to main changes made to `4.12.0`.
> Port of fix: use new VERSION.json file

- VERSION.json
|--|
| #343 |
Bump 4.12.0 branch.
> Bump stage to beta1

- VERSION.json
|--|
| #346  |
Bump 4.12.0 branch.
> Bump stage to rc1

- CHANGELOG.md
- VERSION.json
> Bump to 5.0.0

- CHANGELOG.md
- VERSION.json
> Bump to 6.0.0

- CHANGELOG.md
|---|
| #376  |
This PR removes references to 4.12.2 and updates the changelog for 4.13.0
> Removed references to 4.12.2 and updated changelog 4.13.0

- CHANGELOG.md
|---|
| #376  |
This PR removes references to 4.12.2 and updates the changelog for 4.14.0
> Removed references to 4.12.2 and updated changelog 4.14.0

- CHANGELOG.md
|---|
| #376  |
This PR removes references to 4.12.2 and updates the changelog for main
> Removed references to 4.12.2 and updated changelog main

- src/wazuh_testing/modules/remoted/patterns.py
|---|
|https://github.com/wazuh/wazuh/issues/29936|
Rollbacks the changes added in #29813 to the remoted tests.
> Rollback remoted tests

- VERSION.json
Issue: https://github.com/wazuh/qa-integration-framework/issues/385
> Bump enhancement/wqa385-bump-tmp/bumper-wf-test-to-4.13.0-alpha1 branch to 4.13.0-alpha1

- VERSION.json
Issue: https://github.com/wazuh/qa-integration-framework/issues/385
> Bump tmp/bumper-wf-test branch

- .github/workflows/4_bumper_repository.yml
This issue closes #385. Adds a workflow to automate the process of bumping versions and stages.
https://github.com/wazuh/qa-integration-framework/issues/385#issuecomment-2944419325
> Add workflow for automate the bump process

- VERSION.json
Issue: https://github.com/wazuh/wazuh-qa-automation/issues/1517
> Bump test/wqa2126-fix-secret-reference branch

- .github/workflows/4_bumper_repository.yml
This PR updates the environment secret used during repository checkout
https://github.com/wazuh/qa-integration-framework/actions/runs/15560025396
To delete: https://github.com/wazuh/qa-integration-framework/tree/test/wqa2126-fix-secret-reference
- https://github.com/wazuh/qa-integration-framework/issues/385
- https://github.com/wazuh/wazuh-qa-automation/issues/2126
> Fix repository bumper workflow environment secret

- CHANGELOG.md
- VERSION.json
|--|
| #398  |
- Bump 4.13.0 branch.
>  Bump stage to alpha1

- VERSION.json
Issue: https://github.com/wazuh/qa-integration-framework/issues/385
> Bump change/411-propagate-bumper-to-main branch

- src/wazuh_testing/modules/modulesd/syscollector/patterns.py
Related issue 
- https://github.com/wazuh/wazuh/issues/29652
- https://github.com/wazuh/wazuh/issues/29957
> Integration tests fixed for syscollector extended sources

- CHANGELOG.md
- VERSION.json
Merge branch `4.13.0` into `4.13.1`.
> Merge 4.13.0 into 4.13.1

- CHANGELOG.md
- src/wazuh_testing/modules/authd/utils.py
Merge branch 4.13.0 into 4.14.0
> Merge 4.13.0 into 4.14.0

- src/wazuh_testing/tools/simulators/agent_simulator.py
Closes https://github.com/wazuh/wazuh/issues/31580. 
- It changes the remoted message in the Agent simulator according to the fix at https://github.com/wazuh/wazuh/pull/31254.
Workflow: https://github.com/wazuh/wazuh/actions/runs/17292400950
> Modify remoted message in agent simulator for 4.14.0

- src/wazuh_testing/tools/simulators/agent_simulator.py
Closes https://github.com/wazuh/wazuh/issues/31580. 
- It changes the remoted message in the Agent simulator according to the fix at https://github.com/wazuh/wazuh/pull/31254.
Workflow : https://github.com/wazuh/wazuh/actions/runs/17292401317
> Modify remoted message in agent simulator for 4.14.1

- src/wazuh_testing/modules/modulesd/syscollector/patterns.py
Related issue 
- https://github.com/wazuh/wazuh-agent/issues/805
> Add integration tests for syscollector browser extensions

- CHANGELOG.md
- src/wazuh_testing/modules/modulesd/syscollector/patterns.py
Merge branch 4.14.0 into branch 4.14.1
> Merge 4.14.0 into 4.14.1

- CHANGELOG.md
Part of https://github.com/wazuh/qa-integration-framework/issues/497. Merges the `4.14.1` into the `main` branch.
> Merge 4.14.1 into main
